In [1]:
from MLModel import *

In [9]:
# model argument can be
# 1. SVR, LinearSVR
# 2. DecisionTreeRegressor
# 3. RandomForestRegressor
# 4. AdaBoostRegressor
# 5. GradientBoostingRegressor
# 6. XGBRFRegressor
# 7. LGBMRegressor
# 8. KNeighborsRegressor
# 9. lgb.LGBMRegressor
# 10. xgb.XGBRegressor
model = MLModel(model=AdaBoostRegressor)

# after assign MLModel Class, load_data from local filesystem
model.load_data('data/final_pca_modified.csv')

# Need To make Search
# best_params, best_scores = model.fit_model_with_Gridsearch(param_grid = {'learning_rate': (0.005, 0.01),
#                 'n_estimators' : (30, 60, 90)})
# # max_params = best_params
# print(best_params, best_scores)
# set parameters to make Model
best_params = {'learning_rate': 0.005, 'n_estimators': 30}
'''
best_params = {
    'colsample_bytree': 1.0,
    'gamma': 8.75239267900182,
    'max_depth': 7,
    'min_child_weight': 7.0,
    'reg_alpha': 7.0,
    'reg_lambda': 1.282397381262159,
    'scale_pos_weight': 1.4538566545153988,
    'subsample': 0.7102431062533778,
    'objective': 'binary:logistic',
    'learning_rate': 0.02,
    'random_state': 1991
}
'''
# fit model by parameters and set threshold to see metric scores
# Can also use Sampler Like TomekLinks or SMOTE in here, But Need Much Time
for threshold in np.arange(0.06, 0.1, 0.01):
    model.fit_model(model_params=best_params, threshold=threshold, n_splits=5)


**************************************** 폴드 1 / 폴드 5 ****************************************
[[15171  3910]
 [  624   284]]
정확도: 0.7732, 정밀도: 0.0677, 재현율: 0.3128, F1: 0.1113
[[18832  5021]
 [  771   363]]
정확도: 0.7682, 정밀도: 0.0674, 재현율: 0.3201, F1: 0.1114
**************************************** 폴드 2 / 폴드 5 ****************************************
[[15194  3888]
 [  645   262]]
정확도: 0.7732, 정밀도: 0.0631, 재현율: 0.2889, F1: 0.1036
[[18873  4980]
 [  776   358]]
정확도: 0.7696, 정밀도: 0.0671, 재현율: 0.3157, F1: 0.1106
**************************************** 폴드 3 / 폴드 5 ****************************************
[[15055  4027]
 [  628   279]]
정확도: 0.7671, 정밀도: 0.0648, 재현율: 0.3076, F1: 0.107
[[18773  5080]
 [  765   369]]
정확도: 0.7661, 정밀도: 0.0677, 재현율: 0.3254, F1: 0.1121
**************************************** 폴드 4 / 폴드 5 ****************************************
[[15356  3726]
 [  649   258]]
정확도: 0.7811, 정밀도: 0.0648, 재현율: 0.2845, F1: 0.1055
[[19181  4672]
 [  786   348]]
정확도: 0.7816, 정밀도: 0.0693, 재